# Project Phoenix Configuration 
# src/main/resources/config.properties
# All values can be overridden by system properties in CI:
#   mvn test -Dbrowser=firefox -Dheadless=true

# Browser Settings 
browser=firefox
# Options: chrome | firefox | edge
headless=false
# Set to true in CI: -Dheadless=true

# URLs 
baseUrl=https://the-internet.herokuapp.com
apiBaseUrl=https://the-internet.herokuapp.com

# Credentials 
validUsername=tomsmith
validPassword=SuperSecretPassword!

# Timeouts (seconds) 
implicitWait=10
explicitWait=15
pageLoadTimeout=30
scriptTimeout=30

#Extent Reports 
reportPath=extent-reports/
reportName=Project Phoenix QA Report By Shebaz Qureshi
reportTitle=Project Phoenix Test Execution Report
screenshotOnFailure=true

#  Retry 
retryCount=1
