package com.phoenix.ui;

import com.phoenix.pages.LoginPage;
import com.phoenix.pages.UploadPage;
import com.phoenix.utils.ConfigReader;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * ============================================================================
 * UploadTest  –  UI Tests for the Document Upload Flow (KYC Critical Path)
 * ============================================================================
 * Mirrors the document upload step of the Merchant KYC onboarding portal.
 * Each test logs in first (upload requires an authenticated session),
 * then interacts with /upload or /dynamic_loading.
 * ============================================================================
 */
public class UploadTest extends BaseTest {

    private static final String VALID_USER  = ConfigReader.get("validUsername");
    private static final String VALID_PASS  = ConfigReader.get("validPassword");
    private static final String TEST_FILE   = "src/test/resources/testdata/kyc-sample.txt";
    private String absoluteTestFile;

    @BeforeClass
    public void prepareTestFile() throws IOException {
        Files.createDirectories(Paths.get("src/test/resources/testdata"));
        File file = new File(TEST_FILE);
        if (!file.exists()) {
            try (FileWriter fw = new FileWriter(file)) {
                fw.write("KYC Sample Document – Project Phoenix Automated Test\n");
                fw.write("Merchant ID: TEST-MERCHANT-BY-SHEBAZ-001\n");
                fw.write("Document Type: Identity Verification\n");
                fw.write("Generated by: Automated test fixture\n");
            }
        }
        absoluteTestFile = file.getAbsolutePath();
        log.info("Test fixture ready: {}", absoluteTestFile);
    }

    // ── Happy Path ────────────────────────────────────────────────────────────

    @Test(
        groups      = {"ui", "upload", "smoke"},
        description = "Upload a .txt document and confirm the filename in the response",
        priority    = 1
    )
    public void testSuccessfulFileUpload() {
        logStep("Logging in before upload (KYC portal requires authentication)");
        new LoginPage().open().login(VALID_USER, VALID_PASS);

        logStep("Navigating to upload page");
        UploadPage uploadPage = new UploadPage().open();
        uploadPage.assertOnUploadPage();

        logStep("Selecting and uploading file: kyc-sample.txt");
        uploadPage.uploadFile(absoluteTestFile);

        logStep("Verifying uploaded filename in confirmation");
        uploadPage.assertUploadSuccess("kyc-sample.txt");
        logPass("File upload confirmed – filename 'kyc-sample.txt' present");
    }

    @Test(
        groups      = {"ui", "upload", "smoke"},
        description = "Upload page should be accessible immediately after login",
        priority    = 2
    )
    public void testUploadPageAccessibleAfterLogin() {
        logStep("Login and verify upload page loads");
        new LoginPage().open().login(VALID_USER, VALID_PASS);
        new UploadPage().open().assertOnUploadPage();
        logPass("Upload page is accessible post-login");
    }

    // ── Dynamic Content ───────────────────────────────────────────────────────

    @Test(
        groups      = {"ui", "upload", "dynamic"},
        description = "Trigger a dynamically-loaded element – simulates async KYC status update",
        priority    = 3
    )
    public void testDynamicContentLoading() {
        logStep("Login required for dynamic content page");
        new LoginPage().open().login(VALID_USER, VALID_PASS);

        logStep("Triggering dynamic element (simulates async KYC document verification status)");
        UploadPage uploadPage = new UploadPage();
        String result = uploadPage.triggerAndWaitForDynamicContent();

        logStep("Verifying dynamic element text");
        Assert.assertTrue(
            result.contains("Hello World!"),
            "Expected 'Hello World!' in dynamic element, got: " + result
        );
        logPass("Dynamic element loaded successfully: '" + result + "'");
    }

    // ── File Input Validation ─────────────────────────────────────────────────

    @Test(
        groups      = {"ui", "upload", "regression"},
        description = "File input element must be present and enabled on the upload page",
        priority    = 4
    )
    public void testFileInputElementPresent() {
        logStep("Login and open upload page");
        new LoginPage().open().login(VALID_USER, VALID_PASS);
        UploadPage uploadPage = new UploadPage().open();

        logStep("Verifying file input is present");
        uploadPage.assertOnUploadPage();

        // Verify that selecting a file does not throw
        logStep("Selecting file to verify input accepts it");
        uploadPage.selectFile(absoluteTestFile);
        logPass("File input is present and accepted the file selection");
    }

    @Test(
        groups      = {"ui", "upload", "regression"},
        description = "Submitting without a file should not crash the application",
        priority    = 5
    )
    public void testSubmitWithoutFileHandlesGracefully() {
        logStep("Login and navigate to upload page");
        new LoginPage().open().login(VALID_USER, VALID_PASS);
        UploadPage uploadPage = new UploadPage().open();

        logStep("Clicking upload without selecting a file");
        uploadPage.clickUpload();

        // Application should remain navigable (no 500 error, no crash)
        String currentUrl = uploadPage.getCurrentUrl();
        Assert.assertNotNull(currentUrl, "Page URL should still be accessible");
        Assert.assertFalse(currentUrl.isEmpty(), "Page URL should not be empty");
        logPass("Application handled no-file submission gracefully. URL: " + currentUrl);
    }
}
